### ISSUE TITLE
Shortcuts no longer work

### ISSUE THREAD

**Issue by denizetkar** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#10]
OS: Windows 10
Browser: Google Chrome, Version 86.0.4240.193 (Official Build) (64-bit)

I have the latest version of this chrome extension running on my browser. But none of the shortcut functionality works at the moment (e.g. ALT+d to delete text, ALT+0 to swap languages etc.).

**Comment by yamayamayamaji** [comment]
Thanks for your report.

There have been a some reports of the extension not working, but it seems to be working fine for most users.
Of course, it's working in my environment as well.

Would you please help me to find the cause of the problem?

First, Please try the following steps.

1. Reset the extension's key settings.
   * Open the extension's options page and press the [reset settings] button.
2. If you are using Google Translate, you will be prompted to enter the extension's key settings.
   * Press Ctrl+Shift+R on the Google Translate page.

**Comment by denizetkar** [comment]
Thank you for the prompt reply. I tried the steps you suggested.
1. I did reset the extension's key settings from "reset settings" button in the extension options,
2. When I opened up a new Google Translate tab, I was not prompted to enter key settings or anything like that. Nonetheless, I pressed Ctrl+Shift+R which caused the page to refresh.

Still, none of the shortcuts were working as they did in the past.

**Comment by yamayamayamaji** [comment]
Thanks for your cooperation.

The next thing I would like to see is the url of the Google Translate page you are using.

As an example, I'm using
https://translate.google.com/

**Comment by yamayamayamaji** [comment]
I have found that the extension does not work when you view Google Translate at the following URL
https://translate.google.fr/

This URL seems to deliver the old pattern UI.
This is the reason why the extension for the new UI will not work.

I will consider how to deal with it.

**Comment by denizetkar** [comment]
Here is the URL of my google translate tab: https://translate.google.com/

**Comment by CostelRotari** [comment]
> Here is the URL of my google translate tab: https://translate.google.com/

same here, doesn't work on the .com site either. I v tried all the steps suggested and also reinstall the extension. had this issue starting +- 2w ago. if you have some suggestions I will try them out. One thing I will say the setting window is very little ... can't resize it ... of course scrolling up down, sideways you can reach all the menu but don't remember was like this before.
the app itself is great. I want to thankyou for it. 
![image](https://user-images.githubusercontent.com/31796385/99732973-bb561380-2ac0-11eb-818e-6fe8e792a93b.png)

**Comment by CostelRotari** [comment]
wow! seams that for Edge browser the app does NOT work! I've just try it on Chrome and even the French one  works..... will be nice if you could give it a look even if, we Edge users are not so many.... :(

> I have found that the extension does not work when you view Google Translate at the following URL
> https://translate.google.fr/
> 
> This URL seems to deliver the old pattern UI.
> This is the reason why the extension for the new UI will not work.
> 
> I will consider how to deal with it.

**Comment by denizetkar** [comment]
It works now with the latest update in Google Chrome. Thank you @yamayamayamaji !
