### ISSUE TITLE
Firefox plugin stopped working

### ISSUE THREAD

**Issue by PrintScr** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#12]
I am sorry if I am being too pushy, you are probably aware of it, but firefox plugin stopped working... It is such an amazing plugin and it is so painful to use google translate without it! :)

For some reason it is not always reproducible. What I managed to find out, is that if you try to visit some google translator domain for the first time (e.g try out some .ee, .se, .de domains, you probably haven't ever visited them) then this plugin works perfectly (you will also see some a popup with terms and conditions that you have to agree with). However, once I revisit the same domain, the plugin no longer works.

I also saved the HTML of the both pages:
1. html when the plugin works: https://pastebin.com/PL2NVUrY
2. html when the plugin no longer works (second visit): https://pastebin.com/14sj7Xrf

**Comment by yamayamayamaji** [comment]
Thanks for your report.

I released the latest version 2.7.1.1 a few days ago.
Are you using version 2.7.1.1?

I checked on some domains in the example (.ee, .se, .de) ,
but I could not reproduce the extension not working.
(In all cases, it worked fine.)

**Comment by PrintScr** [comment]
Yep, thank you, apparently I was using the old version of the plugin, now it works
