### ISSUE TITLE
13,october keyboard-shortcuts doesn't work

### ISSUE THREAD

**Issue by masterpices01** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#19]
Ha ha i really love to use this shortcut extension

hope this extension gonna be fixed soon.

**Comment by bulenterdemir** [comment]
I have the same problem. It used to work yesterday. I'm using Chrome and Brave on a MacOS.

**Comment by masterpices01** [comment]
> 

I've create another google translate shortcut at 

[https://github.com/masterpices01/Keyboard-Shortcuts-for-Google-Translate-simplified-](url)

it's a shallow version and only support clear and listen feature for source text

You can intall this stript on temperMonkey as a shorterm replacement

waiting for author to update this extension

**Comment by mariocynicys** [comment]
It doesn't work for me on firefox. + I can't find the settings page on firefox.
