### ISSUE TITLE
Feedback on "Keyboard Shortcuts for Google Translate"

### ISSUE THREAD

**Issue by iddoj** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#2]
I have some feedback on the Google Chrome extension "Keyboard Shortcuts for Google Translate" (for Windows 7)

First of all, I am using it extensively and as a keyboard- and mouse-shortcut fan in general it is very helpful.

Things that are missing and would be good if they can be added:

* (would be very useful) in both the source language and target language selection: shortcut for the pulldown to select a language from the full list and then browse with arrow keys (as opposed to just 3 shortcuts for each). e.g. alt-8 and alt-9.
* (lower priority in my view) ability to customize shortcuts

It would be great if you can let me know if there are any intentions for that, or alternatively contact me for any clarifications you need on my requests.

Thanks, Iddo Jacobi.

**Comment by yamayamayamaji** [comment]
Thank you for your feedback.:smile:

OK, I think I will add shortcut for language selection buttons.

(ability to customize shortcuts  maybe in the future :wink:)

**Comment by yamayamayamaji** [comment]
Released ver1.3.3.0 .

alt-8 and alt-9 added :smile:

**Comment by iddoj** [comment]
Thank you: Just what I was looking for.
