### ISSUE TITLE
Copy feature is not working anymore

### ISSUE THREAD

**Issue by projectx7** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#21]
Amazing shortcut, cant find any better, i've been using it and it works flawlessly but recently (not sure exactly when but like in the past month probably) there (i think) has been an update on the Google Translate website app and the Alt + C is not working anymore because the {c} is not showing anymore under the Copy sign, 
![image](https://user-images.githubusercontent.com/125705489/219811689-53ac8590-1124-46eb-8564-804a2d23a057.png)

Idk exactly what's going on but please fix it :)) Otherwise amazing help with the tool and right now I am not making money off of the idea that I've put it to help me but I promise to tip you 500$ once my thing works, hopefully by the end of 2023 (I mean it, your tool has been a great help)

**Comment by K0stov** [comment]
I’m also looking forward to this getting fixed.

**Comment by yamayamayamaji** [comment]
fixed.
