### ISSUE TITLE
Button for Translate

### ISSUE THREAD

**Issue by notuntoward** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#3]
This is a very useful extension -- thanks for writing it.  One thing I think would make it even better would be the addition of a shortcut for the blue Translate button.  When I enter a lot of text, translation doesn't happen automatically, and won't happen until that button is clicked.  Being able to trigger translation as I write using a keyboard shortcut would be a nice luxury.

**Comment by yamayamayamaji** [comment]
Thank you for your request.:smile:

ok, I think I will add shortcut for translate button.

**Comment by notuntoward** [comment]
Domo arigato!

Scott

**Comment by yamayamayamaji** [comment]
Released ver1.3.3.0 .

shift + enter is added for the blue Translate button.:smile:

**Comment by notuntoward** [comment]
Thanks much,

Scott
