### ISSUE TITLE
Feedback and suggestions: Focus on source entry; customization

### ISSUE THREAD

**Issue by iddoj** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#5]
I have some feedback on the Google Chrome extension "Keyboard Shortcuts for Google Translate" (for Windows 7)

I am using it extensively, and as a keyboard- and mouse-shortcut fan in general it is very helpful for me. And thank you for going through with a previous issue and taking my suggesion seriously.

a) I have another suggestion for shortcut: Focus on Source entry text. Today, if I did any operation outside of the source entry box (e.g. "copy result" whether by shortcut or directly through the button) - I need to use the mouse in order to return to the source entry. True, if I want to enter a completely new text I can do it through "delete source" (alt-d) but if I just want to modify it I can't. That is a very common use-case, from my experience.
A workaround is to use "alt-0" twice (not sure if it's a feature or an unplanned behavior), but it would be better to do it directly.

b) The "readme" says: "[key]s are customizable.(from ver 2.0)"
I seem to be using "Version: 2.0.0.0" but I don't see where they can be customizable. Not a big deal but would be nice to document in case it's still needed. (or remove that comment if not true in that version).
One small reason why customization would be good: If someone is constantly switching between languages with different keyboard layouts, they would prefer using those keys that don't change position between keyboards.
e.g. in English and Hungarian, the symbols "0", "y", "z" are located in different places, so for "swap languages" something other than "alt-0" may be used.

Thanks, Iddo Jacobi.

**Comment by yamayamayamaji** [comment]
Thanks for your feedback.

a) OK, I think I will try to add shortcut to Focus on Source entry text.
  (maybe the next version)

b) I was edited readme.
  You can customize at options page of the extension.
  Options link is shown on the extensions management page at chrome://extensions
  or right clicking the extension icon at address bar.

**Comment by yamayamayamaji** [comment]
ver2.0.1.0 was released.:smile:

alt + f is added for focus on source textarea.

**Comment by iddoj** [comment]
Thank you very much. You have literally made my life (a little but significantly) easier. I simply happen to use Google Translate a lot, and being able to rely on shortcuts is a big help in my opinion.

**Comment by yamayamayamaji** [comment]
Thank you for a lot of appreciative words.:blush:
It gives me more motivation.
