### ISSUE TITLE
Selected language tab

### ISSUE THREAD

**Issue by silverqx** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#7]
Blue line under selected language is broken.

![active_tab](https://user-images.githubusercontent.com/86900/49329032-ce8d1300-f579-11e8-9cea-acfc74816bf5.png)

**Comment by sadrux** [comment]
"Copy" function is not working too, (select and lang area is ok)

**Comment by yamayamayamaji** [comment]
My extention has been some improved.
Please check if your problem was resolved.

**Comment by sadrux** [comment]
> My extention has been some improved.
> Please check if your problem was resolved.

The "Copy" function is still not working
