### ISSUE TITLE
Copy shortcut

### ISSUE THREAD

**Issue by darkzbaron** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#8]
Hi there, great job in adapting to the new layout so quickly. Any chance to have the "Copy translation" shortcut back?

Thanks very much in advance.

Kind regards, Jonathan

**Comment by darkzbaron** [comment]
Thanks Dev!

**Comment by yamayamayamaji** [comment]
Hi darkzbaron,

My extention has been some improved.
Please check if your problem was resolved.
