### ISSUE TITLE
Change "Pivot" key

### ISSUE THREAD

**Issue by mrxdkox** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#9]
Hello. Is it possible to change "Pivot" key to another key? I have remapped keyboard, so it's hard to reach "Alt" button. Would be nice if it will be possible to use "Ctrl" or different button for the main modifier key. And thank you, for your extension.

**Comment by yamayamayamaji** [comment]
Thank you for your inquiry.

If you are using a Mac, you can use "alt" or "control" as a pivot key.

On Windows, the "Ctrl" key (+ Number or Alphabet) is used as a shortcut for Chrome.
(https://support.google.com/chrome/answer/157179?co=GENIE.Platform%3DDesktop&hl=en&oco=0)
I don't want to interfere with this.
